# file importing code builder
import os

pyRootRoute = './src/resource/'
rootRoute = '../../resource/'
saveRootRoute = './src/Maisim/resourceReaders/'


def tip(fo):
    fo.write("// This file is automatically generated by _codebuilder.py.\n// これは _codebuilder.py で自動的に生成したファイルです。\n// 这个文件是由 _codebuilder.py 自动生成的。\n\n")


def outlineIcons():
    dictName = 'maimai_img/outline'
    root = rootRoute + dictName + '/'
    iconNames = [f.split('.')[0] for f in os.listdir(
        pyRootRoute + dictName) if f.endswith('.png')]

    fo = open(saveRootRoute + "outlineIconReader.ts", "w", encoding="utf-8")
    fo.seek(0)
    tip(fo)

    # import list
    for name in iconNames:
        fo.write("import " + name + "_icon from '" +
                 root + name + ".png';\n")

    fo.write('\n')

    # object
    fo.write('export const OutlineIcon = {\n')
    for name in iconNames:
        fo.write("    " + name + ": "+name + "_icon,\n")
    fo.write("};\n")

    fo.close()


def effectsIcons():
    dictName = 'maimai_img/effect'
    root = rootRoute + dictName + '/'
    iconNames = [f.split('.')[0] for f in os.listdir(
        pyRootRoute + dictName) if f.endswith('.png')]

    fo = open(saveRootRoute + "effectIconReader.ts", "w", encoding="utf-8")
    fo.seek(0)
    tip(fo)

    # import list
    for name in iconNames:
        fo.write("import " + name + "_icon from '" +
                 root + name + ".png';\n")

    fo.write('\n')

    # object
    fo.write('export const EffectIcon = {\n')
    for name in iconNames:
        fo.write("    " + name + ": new Image(),\n")

    fo.write("};\n")

    fo.write('\n')

    # init
    fo.write('export const initeffecticons = (onload: () => void) => {\n')
    fo.write("  const amount = " + str(len(iconNames)) + ";\n")
    fo.write("  let loaded = 0;\n")
    for name in iconNames:
        fo.write("  EffectIcon." + name + ".src = " + name + "_icon;\n")
        fo.write("  EffectIcon." + name +
                 ".onload = () => { loaded++; if (loaded >= amount) onload(); }\n")
    fo.write("};\n")
    fo.close()


def notesIcons():
    dictName = 'maimai_img/notes'
    root = rootRoute + dictName + '/'
    iconNames = [f.split('.')[0] for f in os.listdir(
        pyRootRoute + dictName) if f.endswith('.png')]

    fo = open(saveRootRoute + "noteIconReader.ts", "w", encoding="utf-8")
    fo.seek(0)
    tip(fo)

    # import list
    for name in iconNames:
        fo.write("import " + name + "_icon from '" +
                 root + name + ".png';\n")

    fo.write('\n')

    # object
    fo.write('export const NoteIcon = {\n')
    for name in iconNames:
        fo.write("    " + name + ": new Image(),\n")

    fo.write("};\n")

    fo.write('\n')

    # init
    fo.write('export const initnotesicons = (onload: () => void) => {\n')
    fo.write("  const amount = " + str(len(iconNames)) + ";\n")
    fo.write("  let loaded = 0;\n")
    for name in iconNames:
        fo.write("  NoteIcon." + name + ".src = " + name + "_icon;\n")
        fo.write("  NoteIcon." + name +
                 ".onload = () => { loaded++; if (loaded >= amount) onload(); }\n")
    fo.write("};\n")
    fo.close()


def notesSounds():
    dictName = 'sound/note'
    root = rootRoute + dictName + '/'
    soundNames = [f.split('.')[0] for f in os.listdir(
        pyRootRoute + dictName) if f.endswith('.wav')]

    fo = open(saveRootRoute + "noteSoundReader.ts", "w", encoding="utf-8")
    fo.seek(0)
    tip(fo)

    # import list
    for name in soundNames:
        fo.write("import " + name + "_sound from '" +
                 root + name + ".wav';\n")

    fo.write('\n')

    # object
    fo.write('export const NoteSound = {\n')
    for name in soundNames:
        fo.write("    " + name + ": new Audio(),\n")

    fo.write("};\n")

    fo.write('\n')

    # init
    fo.write('export const initnotesounds = (onload: () => void) => {\n')
    fo.write("  const amount = " + str(len(soundNames)) + ";\n")
    fo.write("  let loaded = 0;\n")
    for name in soundNames:
        fo.write("  NoteSound." + name + ".src = " + name + "_sound;\n")
        #fo.write("  NoteSound." + name +
        #         ".onload = () => { loaded++; if (loaded >= amount) onload(); }\n")
        
    fo.write("  onload();\n")
    fo.write("};\n")
    fo.close()


def main():
    notesIcons()
    outlineIcons()
    effectsIcons()
    notesSounds()


if __name__ == '__main__':
    main()
