// This file is automatically generated by _codebuilder.py.
// これは _codebuilder.py で自動的に生成したファイルです。
// 这个文件是由 _codebuilder.py 自动生成的。

import BreakLine_icon from '../../resource/maimai_img/effect/BreakLine.png';
import Circle_icon from '../../resource/maimai_img/effect/Circle.png';
import EachLine_icon from '../../resource/maimai_img/effect/EachLine.png';
import EachLine1_icon from '../../resource/maimai_img/effect/EachLine1.png';
import EachLine2_icon from '../../resource/maimai_img/effect/EachLine2.png';
import EachLine3_icon from '../../resource/maimai_img/effect/EachLine3.png';
import EachLine4_icon from '../../resource/maimai_img/effect/EachLine4.png';
import Firework_icon from '../../resource/maimai_img/effect/Firework.png';
import FireworkCenter_icon from '../../resource/maimai_img/effect/FireworkCenter.png';
import FireworkInnerCircle_icon from '../../resource/maimai_img/effect/FireworkInnerCircle.png';
import Hex_icon from '../../resource/maimai_img/effect/Hex.png';
import mask_icon from '../../resource/maimai_img/effect/mask.png';
import NormalLine_icon from '../../resource/maimai_img/effect/NormalLine.png';
import SlideLine_icon from '../../resource/maimai_img/effect/SlideLine.png';
import StarWhite_icon from '../../resource/maimai_img/effect/StarWhite.png';
import StarYellow_icon from '../../resource/maimai_img/effect/StarYellow.png';
import TouchEff_icon from '../../resource/maimai_img/effect/TouchEff.png';
import UI_GAM_Eff_Effparts_02_icon from '../../resource/maimai_img/effect/UI_GAM_Eff_Effparts_02.png';
import UI_GAM_Eff_Effparts_02_white_icon from '../../resource/maimai_img/effect/UI_GAM_Eff_Effparts_02_white.png';

export const EffectIcon = {
    BreakLine: new Image(),
    Circle: new Image(),
    EachLine: new Image(),
    EachLine1: new Image(),
    EachLine2: new Image(),
    EachLine3: new Image(),
    EachLine4: new Image(),
    Firework: new Image(),
    FireworkCenter: new Image(),
    FireworkInnerCircle: new Image(),
    Hex: new Image(),
    mask: new Image(),
    NormalLine: new Image(),
    SlideLine: new Image(),
    StarWhite: new Image(),
    StarYellow: new Image(),
    TouchEff: new Image(),
    UI_GAM_Eff_Effparts_02: new Image(),
    UI_GAM_Eff_Effparts_02_white: new Image(),
};

export const initeffecticons = (onload: () => void) => {
  const amount = 19;
  let loaded = 0;
  EffectIcon.BreakLine.src = BreakLine_icon;
  EffectIcon.BreakLine.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.Circle.src = Circle_icon;
  EffectIcon.Circle.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.EachLine.src = EachLine_icon;
  EffectIcon.EachLine.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.EachLine1.src = EachLine1_icon;
  EffectIcon.EachLine1.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.EachLine2.src = EachLine2_icon;
  EffectIcon.EachLine2.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.EachLine3.src = EachLine3_icon;
  EffectIcon.EachLine3.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.EachLine4.src = EachLine4_icon;
  EffectIcon.EachLine4.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.Firework.src = Firework_icon;
  EffectIcon.Firework.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.FireworkCenter.src = FireworkCenter_icon;
  EffectIcon.FireworkCenter.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.FireworkInnerCircle.src = FireworkInnerCircle_icon;
  EffectIcon.FireworkInnerCircle.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.Hex.src = Hex_icon;
  EffectIcon.Hex.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.mask.src = mask_icon;
  EffectIcon.mask.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.NormalLine.src = NormalLine_icon;
  EffectIcon.NormalLine.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.SlideLine.src = SlideLine_icon;
  EffectIcon.SlideLine.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.StarWhite.src = StarWhite_icon;
  EffectIcon.StarWhite.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.StarYellow.src = StarYellow_icon;
  EffectIcon.StarYellow.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.TouchEff.src = TouchEff_icon;
  EffectIcon.TouchEff.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.UI_GAM_Eff_Effparts_02.src = UI_GAM_Eff_Effparts_02_icon;
  EffectIcon.UI_GAM_Eff_Effparts_02.onload = () => { loaded++; if (loaded >= amount) onload(); }
  EffectIcon.UI_GAM_Eff_Effparts_02_white.src = UI_GAM_Eff_Effparts_02_white_icon;
  EffectIcon.UI_GAM_Eff_Effparts_02_white.onload = () => { loaded++; if (loaded >= amount) onload(); }
};
