// This file is automatically generated by _codebuilder.py.
// これは _codebuilder.py で自動的に生成したファイルです。
// 这个文件是由 _codebuilder.py 自动生成的。

import break1_sound from '../../resource/sound/note/break1.wav';
import break2_sound from '../../resource/sound/note/break2.wav';
import ex_sound from '../../resource/sound/note/ex.wav';
import firework_sound from '../../resource/sound/note/firework.wav';
import good_sound from '../../resource/sound/note/good.wav';
import great_sound from '../../resource/sound/note/great.wav';
import perfect_sound from '../../resource/sound/note/perfect.wav';
import slide_track_sound from '../../resource/sound/note/slide_track.wav';
import tap_sound from '../../resource/sound/note/tap.wav';
import touch_sound from '../../resource/sound/note/touch.wav';
import touchhold_good_sound from '../../resource/sound/note/touchhold_good.wav';
import touchhold_great_sound from '../../resource/sound/note/touchhold_great.wav';
import touchhold_miss_sound from '../../resource/sound/note/touchhold_miss.wav';
import touchhold_perfect_sound from '../../resource/sound/note/touchhold_perfect.wav';

export const NoteSound = {
    break1: new Audio(),
    break2: new Audio(),
    ex: new Audio(),
    firework: new Audio(),
    good: new Audio(),
    great: new Audio(),
    perfect: new Audio(),
    slide_track: new Audio(),
    tap: new Audio(),
    touch: new Audio(),
    touchhold_good: new Audio(),
    touchhold_great: new Audio(),
    touchhold_miss: new Audio(),
    touchhold_perfect: new Audio(),
};

export const initnotesounds = (onload: () => void) => {
  const amount = 14;
  let loaded = 0;
  NoteSound.break1.src = break1_sound;
  NoteSound.break2.src = break2_sound;
  NoteSound.ex.src = ex_sound;
  NoteSound.firework.src = firework_sound;
  NoteSound.good.src = good_sound;
  NoteSound.great.src = great_sound;
  NoteSound.perfect.src = perfect_sound;
  NoteSound.slide_track.src = slide_track_sound;
  NoteSound.tap.src = tap_sound;
  NoteSound.touch.src = touch_sound;
  NoteSound.touchhold_good.src = touchhold_good_sound;
  NoteSound.touchhold_great.src = touchhold_great_sound;
  NoteSound.touchhold_miss.src = touchhold_miss_sound;
  NoteSound.touchhold_perfect.src = touchhold_perfect_sound;
  onload();
};
