// This file is automatically generated by _codebuilder.py.
// これは _codebuilder.py で自動的に生成したファイルです。
// 这个文件是由 _codebuilder.py 自动生成的。

import hold_icon from '../../resource/maimai_img/notes/hold.png';
import hold_body_icon from '../../resource/maimai_img/notes/hold_body.png';
import hold_each_icon from '../../resource/maimai_img/notes/hold_each.png';
import hold_each_body_icon from '../../resource/maimai_img/notes/hold_each_body.png';
import hold_each_head_icon from '../../resource/maimai_img/notes/hold_each_head.png';
import hold_ex_icon from '../../resource/maimai_img/notes/hold_ex.png';
import hold_ex_body_icon from '../../resource/maimai_img/notes/hold_ex_body.png';
import hold_ex_head_icon from '../../resource/maimai_img/notes/hold_ex_head.png';
import hold_head_icon from '../../resource/maimai_img/notes/hold_head.png';
import hold_miss_icon from '../../resource/maimai_img/notes/hold_miss.png';
import short_hold_icon from '../../resource/maimai_img/notes/short_hold.png';
import short_hold_each_icon from '../../resource/maimai_img/notes/short_hold_each.png';
import short_hold_ex_icon from '../../resource/maimai_img/notes/short_hold_ex.png';
import short_hold_miss_icon from '../../resource/maimai_img/notes/short_hold_miss.png';
import slide_icon from '../../resource/maimai_img/notes/slide.png';
import slide_each_icon from '../../resource/maimai_img/notes/slide_each.png';
import star_icon from '../../resource/maimai_img/notes/star.png';
import star_break_icon from '../../resource/maimai_img/notes/star_break.png';
import star_break_double_icon from '../../resource/maimai_img/notes/star_break_double.png';
import star_double_icon from '../../resource/maimai_img/notes/star_double.png';
import star_each_icon from '../../resource/maimai_img/notes/star_each.png';
import star_each_double_icon from '../../resource/maimai_img/notes/star_each_double.png';
import star_ex_icon from '../../resource/maimai_img/notes/star_ex.png';
import star_ex_double_icon from '../../resource/maimai_img/notes/star_ex_double.png';
import tap_icon from '../../resource/maimai_img/notes/tap.png';
import tap_break_icon from '../../resource/maimai_img/notes/tap_break.png';
import tap_each_icon from '../../resource/maimai_img/notes/tap_each.png';
import tap_ex_icon from '../../resource/maimai_img/notes/tap_ex.png';
import touch_icon from '../../resource/maimai_img/notes/touch.png';
import touch_center_icon from '../../resource/maimai_img/notes/touch_center.png';
import touch_each_icon from '../../resource/maimai_img/notes/touch_each.png';
import touch_each_center_icon from '../../resource/maimai_img/notes/touch_each_center.png';
import touch_each_three_icon from '../../resource/maimai_img/notes/touch_each_three.png';
import touch_each_two_icon from '../../resource/maimai_img/notes/touch_each_two.png';
import touch_hold_1_icon from '../../resource/maimai_img/notes/touch_hold_1.png';
import touch_hold_2_icon from '../../resource/maimai_img/notes/touch_hold_2.png';
import touch_hold_3_icon from '../../resource/maimai_img/notes/touch_hold_3.png';
import touch_hold_4_icon from '../../resource/maimai_img/notes/touch_hold_4.png';
import touch_hold_center_miss_icon from '../../resource/maimai_img/notes/touch_hold_center_miss.png';
import touch_hold_gage_icon from '../../resource/maimai_img/notes/touch_hold_gage.png';
import touch_hold_gage_miss_icon from '../../resource/maimai_img/notes/touch_hold_gage_miss.png';
import touch_hold_miss_icon from '../../resource/maimai_img/notes/touch_hold_miss.png';
import touch_hold_three_icon from '../../resource/maimai_img/notes/touch_hold_three.png';
import touch_hold_two_icon from '../../resource/maimai_img/notes/touch_hold_two.png';
import touch_just_icon from '../../resource/maimai_img/notes/touch_just.png';
import touch_three_icon from '../../resource/maimai_img/notes/touch_three.png';
import touch_two_icon from '../../resource/maimai_img/notes/touch_two.png';
import wifi_icon from '../../resource/maimai_img/notes/wifi.png';
import wifi_each_icon from '../../resource/maimai_img/notes/wifi_each.png';

export const NoteIcon = {
    hold: new Image(),
    hold_body: new Image(),
    hold_each: new Image(),
    hold_each_body: new Image(),
    hold_each_head: new Image(),
    hold_ex: new Image(),
    hold_ex_body: new Image(),
    hold_ex_head: new Image(),
    hold_head: new Image(),
    hold_miss: new Image(),
    short_hold: new Image(),
    short_hold_each: new Image(),
    short_hold_ex: new Image(),
    short_hold_miss: new Image(),
    slide: new Image(),
    slide_each: new Image(),
    star: new Image(),
    star_break: new Image(),
    star_break_double: new Image(),
    star_double: new Image(),
    star_each: new Image(),
    star_each_double: new Image(),
    star_ex: new Image(),
    star_ex_double: new Image(),
    tap: new Image(),
    tap_break: new Image(),
    tap_each: new Image(),
    tap_ex: new Image(),
    touch: new Image(),
    touch_center: new Image(),
    touch_each: new Image(),
    touch_each_center: new Image(),
    touch_each_three: new Image(),
    touch_each_two: new Image(),
    touch_hold_1: new Image(),
    touch_hold_2: new Image(),
    touch_hold_3: new Image(),
    touch_hold_4: new Image(),
    touch_hold_center_miss: new Image(),
    touch_hold_gage: new Image(),
    touch_hold_gage_miss: new Image(),
    touch_hold_miss: new Image(),
    touch_hold_three: new Image(),
    touch_hold_two: new Image(),
    touch_just: new Image(),
    touch_three: new Image(),
    touch_two: new Image(),
    wifi: new Image(),
    wifi_each: new Image(),
};

export const initnotesicons = (onload: () => void) => {
  const amount = 49;
  let loaded = 0;
  NoteIcon.hold.src = hold_icon;
  NoteIcon.hold.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_body.src = hold_body_icon;
  NoteIcon.hold_body.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_each.src = hold_each_icon;
  NoteIcon.hold_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_each_body.src = hold_each_body_icon;
  NoteIcon.hold_each_body.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_each_head.src = hold_each_head_icon;
  NoteIcon.hold_each_head.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_ex.src = hold_ex_icon;
  NoteIcon.hold_ex.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_ex_body.src = hold_ex_body_icon;
  NoteIcon.hold_ex_body.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_ex_head.src = hold_ex_head_icon;
  NoteIcon.hold_ex_head.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_head.src = hold_head_icon;
  NoteIcon.hold_head.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.hold_miss.src = hold_miss_icon;
  NoteIcon.hold_miss.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.short_hold.src = short_hold_icon;
  NoteIcon.short_hold.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.short_hold_each.src = short_hold_each_icon;
  NoteIcon.short_hold_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.short_hold_ex.src = short_hold_ex_icon;
  NoteIcon.short_hold_ex.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.short_hold_miss.src = short_hold_miss_icon;
  NoteIcon.short_hold_miss.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.slide.src = slide_icon;
  NoteIcon.slide.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.slide_each.src = slide_each_icon;
  NoteIcon.slide_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star.src = star_icon;
  NoteIcon.star.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_break.src = star_break_icon;
  NoteIcon.star_break.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_break_double.src = star_break_double_icon;
  NoteIcon.star_break_double.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_double.src = star_double_icon;
  NoteIcon.star_double.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_each.src = star_each_icon;
  NoteIcon.star_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_each_double.src = star_each_double_icon;
  NoteIcon.star_each_double.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_ex.src = star_ex_icon;
  NoteIcon.star_ex.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.star_ex_double.src = star_ex_double_icon;
  NoteIcon.star_ex_double.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.tap.src = tap_icon;
  NoteIcon.tap.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.tap_break.src = tap_break_icon;
  NoteIcon.tap_break.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.tap_each.src = tap_each_icon;
  NoteIcon.tap_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.tap_ex.src = tap_ex_icon;
  NoteIcon.tap_ex.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch.src = touch_icon;
  NoteIcon.touch.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_center.src = touch_center_icon;
  NoteIcon.touch_center.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_each.src = touch_each_icon;
  NoteIcon.touch_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_each_center.src = touch_each_center_icon;
  NoteIcon.touch_each_center.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_each_three.src = touch_each_three_icon;
  NoteIcon.touch_each_three.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_each_two.src = touch_each_two_icon;
  NoteIcon.touch_each_two.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_1.src = touch_hold_1_icon;
  NoteIcon.touch_hold_1.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_2.src = touch_hold_2_icon;
  NoteIcon.touch_hold_2.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_3.src = touch_hold_3_icon;
  NoteIcon.touch_hold_3.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_4.src = touch_hold_4_icon;
  NoteIcon.touch_hold_4.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_center_miss.src = touch_hold_center_miss_icon;
  NoteIcon.touch_hold_center_miss.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_gage.src = touch_hold_gage_icon;
  NoteIcon.touch_hold_gage.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_gage_miss.src = touch_hold_gage_miss_icon;
  NoteIcon.touch_hold_gage_miss.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_miss.src = touch_hold_miss_icon;
  NoteIcon.touch_hold_miss.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_three.src = touch_hold_three_icon;
  NoteIcon.touch_hold_three.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_hold_two.src = touch_hold_two_icon;
  NoteIcon.touch_hold_two.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_just.src = touch_just_icon;
  NoteIcon.touch_just.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_three.src = touch_three_icon;
  NoteIcon.touch_three.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.touch_two.src = touch_two_icon;
  NoteIcon.touch_two.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.wifi.src = wifi_icon;
  NoteIcon.wifi.onload = () => { loaded++; if (loaded >= amount) onload(); }
  NoteIcon.wifi_each.src = wifi_each_icon;
  NoteIcon.wifi_each.onload = () => { loaded++; if (loaded >= amount) onload(); }
};
