// This file is automatically generated by _codebuilder.py.
// これは _codebuilder.py で自動的に生成したファイルです。
// 这个文件是由 _codebuilder.py 自动生成的。

import outline_icon from '../../resource/maimai_img/outline/outline.png';
import Outline_03_icon from '../../resource/maimai_img/outline/Outline_03.png';

export const OutlineIcon = {
    outline: new Image(),
    Outline_03: new Image(),
};

export const initoutlineicons = (onload: () => void) => {
  const amount = 2;
  let loaded = 0;
  OutlineIcon.outline.src = outline_icon;
  OutlineIcon.outline.onload = () => { loaded++; if (loaded >= amount) onload(); }
  OutlineIcon.Outline_03.src = Outline_03_icon;
  OutlineIcon.Outline_03.onload = () => { loaded++; if (loaded >= amount) onload(); }
};
