// This file was automatically generated by _codebuilder.py.
// これは _codebuilder.py で自動的に生成したファイルです。
// 这个文件是由 _codebuilder.py 自动生成的。

import Begin_Tip_icon from '../resource/maimai_img/ui/Begin_Tip.png';
import mamaDX_icon from '../resource/maimai_img/ui/mamaDX.png';
import Outline_00_icon from '../resource/maimai_img/ui/Outline_00.png';
import Outline_01_icon from '../resource/maimai_img/ui/Outline_01.png';
import Outline_02_icon from '../resource/maimai_img/ui/Outline_02.png';
import Outline_03_icon from '../resource/maimai_img/ui/Outline_03.png';
import Outline_04_icon from '../resource/maimai_img/ui/Outline_04.png';
import Outline_05_icon from '../resource/maimai_img/ui/Outline_05.png';
import Outline_06_icon from '../resource/maimai_img/ui/Outline_06.png';
import Outline_07_icon from '../resource/maimai_img/ui/Outline_07.png';
import Outline_08_icon from '../resource/maimai_img/ui/Outline_08.png';
import Outline_09_icon from '../resource/maimai_img/ui/Outline_09.png';
import Outline_10_icon from '../resource/maimai_img/ui/Outline_10.png';
import Outline_11_icon from '../resource/maimai_img/ui/Outline_11.png';
import Outline_12_icon from '../resource/maimai_img/ui/Outline_12.png';
import UI_ADV_Img_LogoMaimaiDX_icon from '../resource/maimai_img/ui/UI_ADV_Img_LogoMaimaiDX.png';
import UI_ADV_Img_PromoChara_icon from '../resource/maimai_img/ui/UI_ADV_Img_PromoChara.png';
import UI_Chara_105810_icon from '../resource/maimai_img/ui/UI_Chara_105810.png';
import UI_CMN_CloudBase_01_icon from '../resource/maimai_img/ui/UI_CMN_CloudBase_01.png';
import UI_CMN_CloudBase_02_icon from '../resource/maimai_img/ui/UI_CMN_CloudBase_02.png';
import UI_CMN_CloudBase_03_icon from '../resource/maimai_img/ui/UI_CMN_CloudBase_03.png';
import UI_CMN_CloudBase_04_icon from '../resource/maimai_img/ui/UI_CMN_CloudBase_04.png';
import UI_LIB_Window_BG_icon from '../resource/maimai_img/ui/UI_LIB_Window_BG.png';

export const uiIcon = {
    Begin_Tip: Begin_Tip_icon,
    mamaDX: mamaDX_icon,
    Outline_00: Outline_00_icon,
    Outline_01: Outline_01_icon,
    Outline_02: Outline_02_icon,
    Outline_03: Outline_03_icon,
    Outline_04: Outline_04_icon,
    Outline_05: Outline_05_icon,
    Outline_06: Outline_06_icon,
    Outline_07: Outline_07_icon,
    Outline_08: Outline_08_icon,
    Outline_09: Outline_09_icon,
    Outline_10: Outline_10_icon,
    Outline_11: Outline_11_icon,
    Outline_12: Outline_12_icon,
    UI_ADV_Img_LogoMaimaiDX: UI_ADV_Img_LogoMaimaiDX_icon,
    UI_ADV_Img_PromoChara: UI_ADV_Img_PromoChara_icon,
    UI_Chara_105810: UI_Chara_105810_icon,
    UI_CMN_CloudBase_01: UI_CMN_CloudBase_01_icon,
    UI_CMN_CloudBase_02: UI_CMN_CloudBase_02_icon,
    UI_CMN_CloudBase_03: UI_CMN_CloudBase_03_icon,
    UI_CMN_CloudBase_04: UI_CMN_CloudBase_04_icon,
    UI_LIB_Window_BG: UI_LIB_Window_BG_icon,
};
